### ISSUE TITLE
How do I update the exec, discover the addresses

### ISSUE THREAD

**Issue by jordann7778** [Mememan55/fivem_trashexec_v2#1]
How do I update the exec, discover the addresses

**Comment by machinetherapist** [comment]
easiest way to find with ce

**Comment by jordann7778** [comment]
what? @machinetherapist

**Comment by jordann7778** [comment]
**how can i find out?** @machinetherapist

**Comment by machinetherapist** [comment]
> **how can i find out?** @machinetherapist

just use debugger lol

**Comment by jordann7778** [comment]
You have discord ? @machinetherapist
